### ISSUE TITLE
Enable to call current rake task equivalent code via API

### ISSUE THREAD

**Issue by sanak** [bizyman/redmine_mail_reminder#4]
This seems to be preferable when creating Docker Redmine image.

@eyewritecode 
Could you check whether this is possible ?  
Thanks,

**Comment by eyewritecode** [comment]
@sanak One way i can think of would be to add endpoints in a controller that executes different tasks when called but i don't think this is a good solution.

Since calling multiple process seem to be an issue, can't something like `whenever` gem fix this? You would only have to launch rails and `whenever` will take care of cron jobs (through rails)

**Comment by sanak** [comment]
@eyewritecode 
Sorry, I forgot to explain the details, but Docker seems to require multiple process (like both Redmine and cron), and that is the reason why I created issue.
`whenever` seems to use `cron` as back ground, so I think that using `whenever` will not solve Docker multiple process issue.
By the way, I don't have experience about Rails `Active Job`, but do you know about this well ?
https://guides.rubyonrails.org/v5.2/active_job_basics.html
If you know about it, do you think that it can be replaceable from current cron job to `Active Job` ?

**Comment by sanak** [comment]
Well, I am going to archive this repo, so I close this PR. 🙇‍♂️
